name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: vranjan041/to_do
      DOCKER_TAG: latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Backend Docker Image
        run: |
          docker build -t $DOCKER_IMAGE_NAME-backend:$DOCKER_TAG -f Dockerfile.backend .

      - name: Build Frontend Docker Image
        run: |
          docker build -t $DOCKER_IMAGE_NAME-frontend:$DOCKER_TAG -f Dockerfile.frontend .

      - name: Log in to DockerHub
        run: |
          echo ${{ secrets.password }} | docker login -u ${{ secrets.username }} --password-stdin

      - name: Push Backend Docker Image to DockerHub
        run: |
          docker push $DOCKER_IMAGE_NAME-backend:$DOCKER_TAG

      - name: Push Frontend Docker Image to DockerHub
        run: |
          docker push $DOCKER_IMAGE_NAME-frontend:$DOCKER_TAG

  run_deployment_on_minikube:
    name: Run on kubernetes cluster
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: start minikube
        uses: medyagh/setup-minikube@v0.0.16

      - name: Get pods
        run: kubectl get pods -A

      - name: checkout repo
        uses: actions/checkout@v3

      - name: Run backend deployment
        run: kubectl apply -f Deployment_bk.yaml

      - name: Run frontend deployment
        run: kubectl apply -f Deployment_fr.yaml

      - name: Wait for the pods to be ready
        run: kubectl wait --for=condition=ready pod --all --timeout=300s

      - name: kubectl get pods and svc
        run: |
          kubectl get pods
          kubectl get svc

      - name: Output Backend
        run: curl http://192.168.49.2:30005/

      - name: Output Frontend
        run: curl http://192.168.49.2:30006/

      - name: Wait for the backend service to be ready
        run: |
          while ! minikube service backend-service --url; do
            echo "Waiting for backend service to be ready..."
            sleep 10
          done

      - name: Wait for the frontend service to be ready
        run: |
          while ! minikube service frontend-service --url; do
            echo "Waiting for frontend service to be ready..."
            sleep 10
          done

      - name: Run services
        run: |
          docker run -d -p 5000:5000 $DOCKER_IMAGE_NAME-backend:$DOCKER_TAG
          docker run -d -p 5173:5173 $DOCKER_IMAGE_NAME-frontend:$DOCKER_TAG

      - name: Wait for testing
        run: |
          echo "Waiting for 4 minutes to allow testing..."
          sleep 240  # 240 seconds = 4 minutes

      # - name: Check service accessibility
      #   run: |
      #     curl http://192.168.49.2:30005/ || echo "Backend service not reachable"
      #     curl http://192.168.49.2:30006/ || echo "Frontend service not reachable"
